package de.soderer.utilities.mail.dkim;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.Signature;
import java.security.SignatureException;
import java.security.interfaces.RSAPrivateKey;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import de.soderer.utilities.mail.dkim.utilities.IoUtilities;
import de.soderer.utilities.mail.dkim.utilities.Utilities;
import jakarta.mail.MessagingException;
import jakarta.mail.Session;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeUtility;

/**
 * MimeMessage, which adds a DKIM signature (RFC 6376, algorithm rsa-sha256) when it is written.
 * <p>
 * Example:
 * <pre>
 * DkimSignedMessage message = new DkimSignedMessage(session, null);
 * message.setFrom(new InternetAddress("sender@example.com"));
 * ...
 * message.setDkimKeyData("example.com", "selector", privateKey, null);
 * Transport.send(message);
 * </pre>
 * <p>
 * All header lines, which are written, are signed except the headers excluded by {@link #setExcludedHeaders(String...)}
 * and those in the ignore list of {@link #writeTo(OutputStream, String[])} (e.g. "Bcc"), which are not written.
 * Without DKIM key data the message is written unsigned.
 */
public class DkimSignedMessage extends MimeMessage {
	/**
	 * Maximum length of the lines of the DKIM-Signature header.
	 */
	private static final int MAXIMUM_MESSAGE_HEADER_LENGTH = 67;

	/**
	 * Message-ID to use or null for a generated Message-ID.
	 */
	private String messageID = null;

	/**
	 * Signing domain (d=).
	 */
	private String domain;
	/**
	 * Key selector (s=).
	 */
	private String selector;
	/**
	 * Private key for signing, or null for unsigned messages.
	 */
	private RSAPrivateKey privateRsaKey;
	/**
	 * Signing identity (i=) or null.
	 */
	private String identity;
	/**
	 * Whether headers are canonicalized "relaxed" instead of "simple".
	 */
	private boolean useRelaxedHeaderCanonicalization = true;
	/**
	 * Whether the body is canonicalized "relaxed" instead of "simple".
	 */
	private boolean useRelaxedBodyCanonicalization = true;
	/**
	 * Lowercase names of headers, which are not signed, or null.
	 */
	private Set<String> excludedHeaderNames = null;

	/**
	 * Creates a message.
	 *
	 * @param session the mail session
	 * @param messageID the Message-ID header value (e.g. "&lt;id@example.com&gt;") or null for a Message-ID generated by Jakarta Mail
	 */
	public DkimSignedMessage(final Session session, final String messageID) {
		super(session);

		this.messageID = messageID;
	}

	/**
	 * Detects characters, which could be used for header injection (CRLF injection) when embedding externally influenced values (domain, selector) unescaped into the DKIM-Signature header.
	 *
	 * @param value the value to check
	 * @return true if the value contains CR, LF or ";"
	 */
	private static boolean containsHeaderInjectionCharacters(final String value) {
		return value.indexOf('\r') >= 0 || value.indexOf('\n') >= 0 || value.indexOf(';') >= 0;
	}

	/**
	 * Sets the given Message-ID or, if none was given, the Message-ID generated by Jakarta Mail.
	 *
	 * @throws MessagingException if the header cannot be set
	 */
	@Override
	protected void updateMessageID() throws MessagingException {
		if (messageID != null) {
			setHeader("Message-ID", messageID);
		} else {
			// Without a given Message-ID, the default generated by Jakarta Mail is used
			super.updateMessageID();
		}
	}

	/**
	 * Sets the data for the DKIM signature. Without this data the message is written unsigned.
	 *
	 * @param domain signing domain (d=), the domain of the DNS record "selector._domainkey.domain" with the public key
	 * @param selector key selector (s=)
	 * @param privateRsaKey RSA private key matching the public key in DNS
	 * @param identity signing identity (i=), e.g. "user@example.com", which must be in the signing domain or one of its subdomains, or null
	 * @throws Exception if a value is missing or invalid
	 */
	public void setDkimKeyData(final String domain, final String selector, final RSAPrivateKey privateRsaKey, final String identity) throws Exception {
		if (Utilities.isBlank(domain)) {
			throw new Exception("DKIM domain may not be empty");
		} else if (containsHeaderInjectionCharacters(domain)) {
			throw new Exception("DKIM domain contains invalid characters");
		} else if (Utilities.isBlank(selector)) {
			throw new Exception("DKIM key selector may not be empty");
		} else if (containsHeaderInjectionCharacters(selector)) {
			throw new Exception("DKIM key selector contains invalid characters");
		} else if (privateRsaKey == null) {
			throw new Exception("DKIM private key may not be empty");
		} else if (identity != null) {
			// RFC 6376: the identity must be in the signing domain or one of its subdomains
			final int atIndex = identity.lastIndexOf('@');
			if (atIndex < 0) {
				throw new Exception("DKIM identity must contain '@': " + identity);
			}
			final String identityDomain = identity.substring(atIndex + 1).toLowerCase(Locale.ROOT);
			final String domainLower = domain.toLowerCase(Locale.ROOT);
			if (!identityDomain.equals(domainLower) && !identityDomain.endsWith("." + domainLower)) {
				throw new Exception("DKIM identity domain '" + identityDomain + "' is not the signing domain '" + domain + "' or one of its subdomains");
			}
		}

		this.domain = domain;
		this.selector = selector;
		this.privateRsaKey = privateRsaKey;
		this.identity = identity;
	}

	/**
	 * Sets the data for the DKIM signature and returns this object for method chaining.
	 *
	 * @param newDomain signing domain (d=)
	 * @param newSelector key selector (s=)
	 * @param newPrivateRsaKey RSA private key matching the public key in DNS
	 * @param newIdentity signing identity (i=) or null
	 * @return this object
	 * @throws Exception if a value is missing or invalid
	 */
	public DkimSignedMessage withDkimKeyData(final String newDomain, final String newSelector, final RSAPrivateKey newPrivateRsaKey, final String newIdentity) throws Exception {
		setDkimKeyData(newDomain, newSelector, newPrivateRsaKey, newIdentity);
		return this;
	}

	/**
	 * Sets the canonicalization algorithms (default "relaxed/relaxed").
	 *
	 * @param useRelaxedHeaderCanonicalization true for "relaxed", false for "simple" header canonicalization
	 * @param useRelaxedBodyCanonicalization true for "relaxed", false for "simple" body canonicalization
	 */
	public void setCanonicalization(final boolean useRelaxedHeaderCanonicalization, final boolean useRelaxedBodyCanonicalization) {
		this.useRelaxedHeaderCanonicalization = useRelaxedHeaderCanonicalization;
		this.useRelaxedBodyCanonicalization = useRelaxedBodyCanonicalization;
	}

	/**
	 * Sets the canonicalization algorithms and returns this object for method chaining.
	 *
	 * @param newUseRelaxedHeaderCanonicalization true for "relaxed", false for "simple" header canonicalization
	 * @param newUseRelaxedBodyCanonicalization true for "relaxed", false for "simple" body canonicalization
	 * @return this object
	 */
	public DkimSignedMessage withCanonicalization(final boolean newUseRelaxedHeaderCanonicalization, final boolean newUseRelaxedBodyCanonicalization) {
		setCanonicalization(newUseRelaxedHeaderCanonicalization, newUseRelaxedBodyCanonicalization);
		return this;
	}

	/**
	 * Sets the names of headers, which are not signed (case insensitive). The "From" header must not be excluded.
	 *
	 * @param headerNames names of the headers not to sign
	 */
	public void setExcludedHeaders(final String... headerNames) {
		// Header names are case insensitive, so they are stored in lowercase
		excludedHeaderNames = new HashSet<>();
		if (headerNames != null) {
			for (final String headerName : headerNames) {
				if (headerName != null) {
					excludedHeaderNames.add(headerName.trim().toLowerCase(Locale.ROOT));
				}
			}
		}
	}

	/**
	 * Sets the names of headers, which are not signed, and returns this object for method chaining.
	 *
	 * @param headerNames names of the headers not to sign (case insensitive)
	 * @return this object
	 */
	public DkimSignedMessage withExcludedHeaders(final String... headerNames) {
		setExcludedHeaders(headerNames);
		return this;
	}

	/**
	 * Writes the message with a DKIM signature as first header, if DKIM key data is set.
	 * The headers in the ignore list are neither written nor signed.
	 *
	 * @param outputStream the stream for the message data
	 * @param ignoreList names of headers, which are not written (e.g. "Bcc"), or null
	 * @throws IOException if writing fails
	 * @throws MessagingException if the message cannot be signed, e.g. without "From" header
	 */
	@Override
	public void writeTo(final OutputStream outputStream, final String[] ignoreList) throws IOException, MessagingException {
		if (privateRsaKey != null) {
			if (!saved) {
				saveChanges();
			}

			// Set the sent date before the header lines are collected, because the "Date" header is signed too
			if (getSentDate() == null) {
				setSentDate(new Date());
			}

			// Get the encoded message body as bytes. It is handled as ISO-8859-1 text, which maps each byte to one character, so 8bit content is kept unchanged.
			final byte[] encodedMessageBody = getEncodedMessageBody();
			final String encodedMessageBodyText = new String(encodedMessageBody, StandardCharsets.ISO_8859_1);

			// Exactly the header lines, which are written, are signed. Headers in the ignoreList (e.g. "Bcc") are neither written nor signed.
			final List<String> headerLines = Collections.list(getNonMatchingHeaderLines(ignoreList));

			// Write dkim signature
			outputStream.write(createDkimSignature(headerLines, encodedMessageBodyText).getBytes(StandardCharsets.UTF_8));
			outputStream.write("\r\n".getBytes(StandardCharsets.UTF_8));

			// Write other headers
			for (final String headerLine : headerLines) {
				outputStream.write(headerLine.getBytes(StandardCharsets.UTF_8));
				outputStream.write("\r\n".getBytes(StandardCharsets.UTF_8));
			}
			outputStream.write("\r\n".getBytes(StandardCharsets.UTF_8));

			// Write the encoded message body
			outputStream.write(encodedMessageBody);
			outputStream.flush();
		} else {
			super.writeTo(outputStream, ignoreList);
		}
	}

	/**
	 * Returns the body of the message in its transfer encoding, exactly as it is written.
	 *
	 * @return the encoded body data
	 * @throws IOException if reading the content fails
	 * @throws MessagingException if encoding the content fails
	 */
	private byte[] getEncodedMessageBody() throws IOException, MessagingException {
		try (ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
			if (modified) {
				try (OutputStream outputStream = MimeUtility.encode(buffer, getEncoding())) {
					getDataHandler().writeTo(outputStream);
				}
			} else if (content == null) {
				try (InputStream inputStream = getContentStream()) {
					IoUtilities.copy(inputStream, buffer);
				}
			} else {
				buffer.write(content);
			}
			return buffer.toByteArray();
		}
	}

	/**
	 * Creates the complete DKIM-Signature header line (without trailing CRLF).
	 *
	 * @param headerLines the header lines, which are written
	 * @param encodedMessageBody the encoded body as ISO-8859-1 text (one character per byte)
	 * @return the DKIM-Signature header line
	 * @throws MessagingException if the "From" header is missing or signing fails
	 */
	private String createDkimSignature(final List<String> headerLines, final String encodedMessageBody) throws MessagingException {
		final Date sentDate = getSentDate();

		final Map<String, String> signatureData = new LinkedHashMap<>();
		signatureData.put("v", "1");
		signatureData.put("a", DkimUtilities.ALLOWED_DKIM_SIGNATURE_ALGORITHM_CODE);
		signatureData.put("c", (useRelaxedHeaderCanonicalization ? DkimUtilities.DKIM_SERIALIZATION_RELAXED_CODE : DkimUtilities.DKIM_SERIALIZATION_SIMPLE_CODE) + "/" + (useRelaxedBodyCanonicalization ? DkimUtilities.DKIM_SERIALIZATION_RELAXED_CODE : DkimUtilities.DKIM_SERIALIZATION_SIMPLE_CODE));
		signatureData.put("d", domain);
		signatureData.put("s", selector);
		signatureData.put("t", Long.toString((sentDate == null ? System.currentTimeMillis() : sentDate.getTime()) / 1000L));
		if (identity != null) {
			signatureData.put("i", DkimUtilities.encodeDkimQuotedPrintable(identity));
		}

		boolean fromHeaderIsIncluded = false;
		final List<String> headerLinesToSign = new ArrayList<>();
		for (final String headerLine : headerLines) {
			final String headerName = DkimUtilities.getHeaderName(headerLine);
			if ((excludedHeaderNames == null || !excludedHeaderNames.contains(headerName.toLowerCase(Locale.ROOT))) && !DkimUtilities.DKIM_SIGNATURE_HEADER_NAME.equalsIgnoreCase(headerName)) {
				headerLinesToSign.add(headerLine);
				if ("from".equalsIgnoreCase(headerName)) {
					fromHeaderIsIncluded = true;
				}
			}
		}

		if (!fromHeaderIsIncluded) {
			throw new MessagingException("Mandatory header 'from' is not included in headers for dkim signature");
		}

		// The header names are listed in order of appearance. For multiple occurrences of a header name, verifiers use the instances from the bottom up,
		// so they are signed in the same order.
		final List<String> headerNames = new ArrayList<>();
		for (final String headerLine : headerLinesToSign) {
			headerNames.add(DkimUtilities.getHeaderName(headerLine));
		}
		final Map<String, LinkedList<String>> headerLinesByName = DkimUtilities.getHeaderLinesByName(headerLinesToSign);
		final StringBuilder serializedHeaderData = new StringBuilder();
		for (final String headerName : headerNames) {
			serializedHeaderData.append(DkimUtilities.canonicalizeHeaderLine(useRelaxedHeaderCanonicalization, headerLinesByName.get(headerName.toLowerCase(Locale.ROOT)).removeLast()));
			serializedHeaderData.append("\r\n");
		}

		MessageDigest bodyHashingMessageDigest;
		try {
			bodyHashingMessageDigest = MessageDigest.getInstance("SHA-256");
		} catch (final NoSuchAlgorithmException e) {
			throw new MessagingException("Unknown hashing algorithm: SHA-256", e);
		}
		final String canonicalBody = DkimUtilities.canonicalizeBody(useRelaxedBodyCanonicalization, encodedMessageBody);
		final byte[] bodyHashBytes = bodyHashingMessageDigest.digest(canonicalBody.getBytes(StandardCharsets.ISO_8859_1));
		final String bodyHashBase64String = Base64.getEncoder().encodeToString(bodyHashBytes);
		signatureData.put("bh", bodyHashBase64String);

		signatureData.put("h", DkimUtilities.serializeHeaderNames(headerNames, 3, MAXIMUM_MESSAGE_HEADER_LENGTH));

		final String serializedSignature = serializeDkimSignatureData(signatureData, DkimUtilities.DKIM_SIGNATURE_HEADER_NAME.length() + 2, MAXIMUM_MESSAGE_HEADER_LENGTH);
		serializedHeaderData.append(DkimUtilities.canonicalizeHeader(useRelaxedHeaderCanonicalization, DkimUtilities.DKIM_SIGNATURE_HEADER_NAME, serializedSignature));

		Signature signature;
		try {
			signature = Signature.getInstance(DkimUtilities.SIGNATURE_ALGORITHM_NAME);
			signature.initSign(privateRsaKey);
		} catch (final NoSuchAlgorithmException e) {
			throw new MessagingException("Unknown signing algorithm SHA256withRSA", e);
		} catch (final InvalidKeyException e) {
			throw new MessagingException("Invalid private key", e);
		}
		byte[] signatureBytes;
		try {
			signature.update(serializedHeaderData.toString().getBytes(StandardCharsets.UTF_8));
			signatureBytes = signature.sign();
		} catch (final SignatureException e) {
			throw new MessagingException("Failed to create signature", e);
		}
		final String signatureBase64String = Base64.getEncoder().encodeToString(signatureBytes);

		return DkimUtilities.DKIM_SIGNATURE_HEADER_NAME + ": " + serializedSignature + serializeBase64String(signatureBase64String, 3, MAXIMUM_MESSAGE_HEADER_LENGTH);
	}

	/**
	 * Folds the base64 signature value into header continuation lines.
	 *
	 * @param base64String the base64 value
	 * @param prefixLength number of characters already used in the first line
	 * @param maxHeaderLength maximum line length
	 * @return the folded value
	 */
	private static String serializeBase64String(final String base64String, int prefixLength, final int maxHeaderLength) {
		int base64StringReadIndex = 0;
		final StringBuilder builder = new StringBuilder();

		while (true) {
			if (prefixLength > 0 && (base64String.substring(base64StringReadIndex).length() + prefixLength) > maxHeaderLength) {
				builder.append(base64String.substring(base64StringReadIndex, base64StringReadIndex + maxHeaderLength - prefixLength));
				base64StringReadIndex += maxHeaderLength - prefixLength;
				prefixLength = 0;
			} else if (2 + base64String.substring(base64StringReadIndex).length() > maxHeaderLength) {
				builder.append("\r\n\t ").append(base64String.substring(base64StringReadIndex, base64StringReadIndex + maxHeaderLength - 2));
				base64StringReadIndex += maxHeaderLength -2;
			} else {
				builder.append("\r\n\t ").append(base64String.substring(base64StringReadIndex));
				break;
			}
		}

		return builder.toString();
	}

	/**
	 * Serializes the DKIM signature tags into folded header lines, ending with an empty "b=" tag.
	 *
	 * @param signatureData the tags and their values in output order
	 * @param prefixLength number of characters already used in the first line
	 * @param maxHeaderLength maximum line length
	 * @return the folded tag list
	 */
	private static String serializeDkimSignatureData(final Map<String, String> signatureData, int prefixLength, final int maxHeaderLength) {
		int position = 0;
		final StringBuilder builder = new StringBuilder();

		for (final Entry<String, String> entry : signatureData.entrySet()) {
			final StringBuilder entryBuilder = new StringBuilder();
			entryBuilder.append(entry.getKey()).append("=").append(entry.getValue()).append(";");

			if (position + entryBuilder.length() + 1 + prefixLength > maxHeaderLength) {
				position = entryBuilder.length();
				builder.append("\r\n\t").append(entryBuilder);
				prefixLength = 0;
			} else {
				builder.append(" ").append(entryBuilder);
				position += 1 + entryBuilder.length();
			}
		}

		// "b=" must be included in serialized signature data
		builder.append("\r\n\t" + "b=");

		return builder.toString().trim();
	}
}
